default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
    -   id: conventional-pre-commit
        stages:
        - commit-msg
        args:
        - add
        - dvc
        - ci
        - docs
        - bug
        - research
        - feat
        - fix
        - refactor
        - revert
        - test
        - security
        - perf
        - resolve
        - maintain
        - merge
        - sagemaker
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-xml
    -   id: mixed-line-ending
        args:
        - --fix=lf
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: debug-statements
    -   id: fix-byte-order-marker
    -   id: forbid-new-submodules
    -   id: forbid-submodules
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: no-commit-to-branch
        args:
        - --branch=main
        - --branch=develop
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-use-type-annotations
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: python-use-type-annotations
    -   id: text-unicode-replacement-char
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.5.1
    hooks:
    -   id: docformatter
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
    -   id: nbqa-check-ast
    -   id: nbqa-isort
        args:
        - --profile=black
    -   id: nbqa-mypy
        args:
        - --config-file=pyproject.toml
    -   id: nbqa-pyupgrade
    -   id: nbqa-pylint
        args:
        - --rcfile=pyproject.toml
-   repo: https://github.com/bwhmather/ssort
    rev: v0.11.6
    hooks:
    -   id: ssort
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    -   id: black
        args:
        - --config=pyproject.toml
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
    -   id: isort
        args:
        - --profile=black
-   repo: https://github.com/PyCQA/pylint
    rev: v2.15.10
    hooks:
    -   id: pylint
        args:
        - --rcfile=pyproject.toml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        args:
        - --config-file=pyproject.toml
        exclude: tests
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    -   id: bandit
        exclude: ^tests/
        args:
        - -r
-   repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
    -   id: nbstripout
-   repo: https://github.com/iterative/dvc
    rev: 2.41.1
    hooks:
    -   id: dvc-pre-commit
        language_version: python3
        stages:
        - commit
    -   id: dvc-pre-push
        language_version: python3
        stages:
        - push
    -   id: dvc-post-checkout
        language_version: python3
        stages:
        - post-checkout
        always_run: true
-   repo: https://github.com/python-poetry/poetry
    rev: 1.3.0
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
        args:
        - --with
        - dev
        - --format
        - requirements.txt
        - --output
        - requirements.txt
