stages:
  train:
    cmd: python src/ml_project_template/training/train.py
    deps:
      - data
      - src
    params:
      - params.yaml:
    outs:
      - models
    metrics:
      - logs/dvc/metrics.json:
          cache: false
    plots:
      - plots:
          cache: false
